### ISSUE TITLE
AttributeError: 'dependencies' object has no attribute 'model'

### ISSUE THREAD

**Issue by goern** [CermakM/argo-python-sdk#2]
**Describe the bug**
```

Traceback (most recent call last):
--
  | File "/opt/app-root/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
  | resp = await task
  | File "/opt/app-root/lib/python3.7/site-packages/octomachinery/app/routing/webhooks_dispatcher.py", line 82, in wrapper
  | return await wrapped_function(request, github_app=github_app)
  | File "/opt/app-root/lib/python3.7/site-packages/octomachinery/app/routing/webhooks_dispatcher.py", line 120, in route_github_webhook_event
  | await dispatch_event(event)
  | File "/opt/app-root/lib/python3.7/site-packages/gidgethub/routing.py", line 80, in dispatch
  | await callback(event, *args, **kwargs)
  | File "app.py", line 138, in on_pr_open_or_sync
  | installation=installation,
  | File "app.py", line 168, in _submit_thamos_workflow
  | wf = ThamosAdviseCheckRun()
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 233, in __init__
  | self.compile()
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 376, in compile
  | self.spec: V1alpha1WorkflowSpec = _compile(self.spec)
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 371, in _compile
  | value: Any = _compile(getattr(obj, attr))
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 368, in _compile
  | return list(map(_compile, obj))
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 371, in _compile
  | value: Any = _compile(getattr(obj, attr))
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 371, in _compile
  | value: Any = _compile(getattr(obj, attr))
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 368, in _compile
  | return list(map(_compile, obj))
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 371, in _compile
  | value: Any = _compile(getattr(obj, attr))
  | File "/opt/app-root/lib/python3.7/site-packages/argo/workflows/sdk/_workflow.py", line 343, in _compile
  | if obj.model is not None:
  | AttributeError: 'dependencies' object has no attribute 'model'


```

**Comment by CermakM** [comment]
Could you provide a reproducer? Tried with Python 3.7.5 and I am not hitting this issue.

**Comment by valayDave** [comment]
I am running running below script and getting similar error. 

```
from argo.workflows.dsl import Workflow

from argo.workflows.dsl.tasks import *
from argo.workflows.dsl.templates import *
from argo.workflows.client import V1alpha1Api
from argo.workflows.config import load_kube_config

namespace = "argo"
v1alpha1 = V1alpha1Api()


class DagDiamond(Workflow):

    @task
    @parameter(name="message", value="A")
    def A(self, message: V1alpha1Parameter) -> V1alpha1Template:
        return self.echo(message=message)

    @task
    @parameter(name="message", value="B")
    @dependencies(["A"])
    def B(self, message: V1alpha1Parameter) -> V1alpha1Template:
        return self.echo(message=message)

    @task
    @parameter(name="message", value="C")
    @dependencies(["A"])
    def C(self, message: V1alpha1Parameter) -> V1alpha1Template:
        return self.echo(message=message)

    @task
    @parameter(name="message", value="D")
    @dependencies(["B", "C"])
    def D(self, message: V1alpha1Parameter) -> V1alpha1Template:
        return self.echo(message=message)

    @template
    @inputs.parameter(name="message")
    def echo(self, message: V1alpha1Parameter) -> V1Container:
        container = V1Container(
            image="alpine:3.7",
            name="echo",
            command=["echo", "{{inputs.parameters.message}}"],
        )

        return container

print(DagDiamond())

load_kube_config()

v1alpha1.create_namespaced_workflow(namespace, DagDiamond())

wfs = v1alpha1.list_namespaced_workflows(namespace=namespace)

```
ERROR 
```
{'api_version': 'argoproj.io/v1alpha1',
 'kind': 'Workflow',
 'metadata': {'generate_name': 'dag-diamond-', 'name': 'dag-diamond'},
 'spec': {'entrypoint': 'main',
          'templates': [{'dag': {'tasks': [{'arguments': {'parameters': [{'name': 'message',
                                                                          'value': 'A'}]},
                                            'name': 'A',
                                            'template': 'echo'},
                                           {'arguments': {'parameters': [{'name': 'message',
                                                                          'value': 'B'}]},
                                            'dependencies': ['A'],
                                            'name': 'B',
                                            'template': 'echo'},
                                           {'arguments': {'parameters': [{'name': 'message',
                                                                          'value': 'C'}]},
                                            'dependencies': ['A'],
                                            'name': 'C',
                                            'template': 'echo'},
                                           {'arguments': {'parameters': [{'name': 'message',                                                                          'value': 'D'}]},
                                            'dependencies': ['B', 'C'],
                                            'name': 'D',
                                            'template': 'echo'}]},
                         'name': 'main'},
                        {'container': {'command': ['echo',
                                                   '{{inputs.parameters.message}}'],
                                       'image': 'alpine:3.7',
                                       'name': 'echo'},
                         'inputs': {'parameters': [{'name': 'message'}]},
                         'name': 'echo'}]},
 'status': {}}
Traceback (most recent call last):
  File "tests_workflow.py", line 52, in <module>
    v1alpha1.create_namespaced_workflow(namespace, DagDiamond())
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 233, in __init__
    self.compile()
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 376, in compile
    self.spec: V1alpha1WorkflowSpec = _compile(self.spec)
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 371, in _compile
    value: Any = _compile(getattr(obj, attr))
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 368, in _compile
    return list(map(_compile, obj))
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 371, in _compile
    value: Any = _compile(getattr(obj, attr))
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 371, in _compile
    value: Any = _compile(getattr(obj, attr))
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 368, in _compile
    return list(map(_compile, obj))
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 371, in _compile
    value: Any = _compile(getattr(obj, attr))
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 371, in _compile
    value: Any = _compile(getattr(obj, attr))
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 368, in _compile
    return list(map(_compile, obj))
  File "/Users/valaydave/Documents/Code-Workspace/ASU-Projects/CSE598-ML-Data-Systems/ML-Systems-Project/kubernetes-testing/.env/lib/python3.7/site-packages/argo/workflows/dsl/_workflow.py", line 343, in _compile
    if obj.model is not None:
AttributeError: 'parameter' object has no attribute 'model'
```
SPECS
-------
OS : Macos
Python 3.7.6
pip install argo-workflows
pip install git+git://github.com/CermakM/argo-python-dsl


What can be the problem ?

**Comment by CermakM** [comment]
Thanks for the reproducer @valayDave! I will investigate further :+1:

**Comment by CermakM** [comment]
@valayDave a fix has been proposed in https://github.com/CermakM/argo-python-dsl/pull/17
